name: eshop-services
services:
  catalogdb:
    image: postgres:15

  basketdb:
    image: postgres:15

  distributedcache:
    image: redis:7-alpine

  identitydb:
    image: postgres:15

volumes:
  postgres_catalog:
    external: true
    name: dockercompose11762921647425945260_postgres_catalog
  postgres_basket:
    external: true
    name: dockercompose11762921647425945260_postgres_basket
  redis_data:
    external: true
    name: dockercompose11762921647425945260_redis_data
  postgres_identity:
    name: eshop_postgres_identity
